services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_HOST: maria_db_app
      DB_USER: root
      DB_PASSWORD: qwert
      DB_DATABASE: tareas
    networks:
      - dokploy-network

  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - deployment_network   

networks:
  deployment_network:
    external: true