
services:
  maria_db_app:
    image: mariadb:10.11.10
    container_name: tareas-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwert
      MYSQL_DATABASE: tareas
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmysqladmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always

    environment:
      PMA_HOST: tareas-db
      PMA_PORT: 3306
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.softapp.ch`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - maria_db_app
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_DATABASE: tareas

  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: {}
